### ISSUE TITLE
File pushing of transitive dependencies doesn't properly cause rebuilds

### ISSUE THREAD

**Issue by tvanderpol** [bitburner-official/bitburner-vscode#10] opened 2022-01-15 04:23 UTC
Firstly, thanks for the plugin! It's nice to use an external editor.

Now that an external editor makes it easy, I've been organising my files a bit better which caused me to run into some difficulties:

My actual scripts are [here](https://github.com/tvanderpol/bitburner_scipts) but the basic problem is this:

Files: 
```
util/logger.js
scheduler/scheduler.js
overmind.js
```

`overmind.js`:
```javascript
import Scheduler from "scheduler/scheduler.js"
```

`scheduler.js`:
```javascript
import Logger from "util/logger.js";
```

logger.js does more or less the obvious.

When I make a change to `logger.js` this gets uploaded to the game. But the entry point for my scripts is `overmind.js` and as far as I can tell, the JS never gets recompiled or transpiled or whatever happens under the hood. As such any changes I make don't happen until I push (I think?) `logger.js`, -then- `scheduler.js` and lastly `overmind.js`, in that order.

I have quite a bit of trouble keeping track of what changes have and haven't actually made it to the game.

I'm not a Javascript expert by any stretch but one thing I'd click on in a heartbeat is an option to bust all the cached transpiled code every time I push up a file. I wouldn't personally care that this might slow things down some in exchange for always executing the code I think I am.

I could just be missing something simpler, would appreciate thoughts!

**Comment by tvanderpol** [comment] 2022-01-15 09:27
Note: I've since seen the same problem while editing files in-game (though I still have the external editor open - I'm just making minor changes to try and bust the cache).

**Comment by paulcdejean** [comment] 2022-01-15 19:27
Dupe of:

https://github.com/danielyxie/bitburner/issues/2413
https://github.com/danielyxie/bitburner/issues/2336
https://github.com/danielyxie/bitburner/issues/2408

But yeah I really hope this gets fixed.

**Comment by tvanderpol** [comment] 2022-01-16 00:00
> Dupe of:
> 
> 
> 
> https://github.com/danielyxie/bitburner/issues/2413
> 
> https://github.com/danielyxie/bitburner/issues/2336
> 
> https://github.com/danielyxie/bitburner/issues/2408
> 
> 
> 
> But yeah I really hope this gets fixed.

Ah right so not related to the plug-in at all. Thank you, I'll close this issue!

**Closed as completed** 2022-01-16 00:00 UTC
